#!/bin/zsh

##
## Usage example to build Chapter 01, Question 01, 'Debug' mode
## % ./ctci6 01 01 Debug
##

## Mode is $3
MODE=$3

if [ -z $3 ]
then
    MODE=Debug
fi

echo "\n[Running make with mode: '"$MODE"'...]\n"
make -C ./build/make/$MODE/$1/$2
echo "\n[Make complete.]\n"

echo "\n[Running '"$0_$1_$2"']\n"
./build/make/$MODE/$1/$2/$0_$1_$2
echo "\n[Process completed.]\n"
